-- Neurocapstone initial database schema
-- Creates the five application tables and enables Row Level Security.
-- Storage buckets were created separately in the Supabase Storage dashboard.

create table public.proteins (
    uniprot_id varchar(16) primary key,
    gene_symbol varchar(32) not null unique,
    canonical_sequence text not null,
    pdb_storage_path text
);

create table public.variants (
    id bigint generated by default as identity primary key,
    uniprot_id varchar(16) not null,
    variant_code varchar(16) not null,
    wild_type_aa char(1) not null,
    mutant_aa char(1) not null,
    position integer not null,

    constraint variants_protein_fk
        foreign key (uniprot_id)
        references public.proteins(uniprot_id)
        on delete cascade,

    constraint variants_unique_protein_variant
        unique (uniprot_id, variant_code),

    constraint variants_position_positive
        check (position > 0)
);

create table public.clinical_cache (
    variant_id bigint primary key,

    clinvar_match boolean,
    clinvar_significance varchar(128),
    clinvar_variation_id varchar(64),
    clinvar_scope varchar(64),

    alphamissense_score real,
    alphamissense_class varchar(64),

    dbsnp_rsid varchar(64),
    lovd_status text,
    clingen_id varchar(128),

    raw_data_json jsonb,

    updated_at timestamptz not null default now(),

    constraint clinical_cache_variant_fk
        foreign key (variant_id)
        references public.variants(id)
        on delete cascade
);

create table public.biophysics_metrics (
    variant_id bigint primary key,

    delta_volume real,
    delta_hydrophobicity real,
    delta_charge real,

    sasa real,
    exposure varchar(32),
    secondary_structure varchar(64),
    plddt_confidence real,

    backbone_strain varchar(128),

    stability_audit_json jsonb,

    updated_at timestamptz not null default now(),

    constraint biophysics_metrics_variant_fk
        foreign key (variant_id)
        references public.variants(id)
        on delete cascade
);

create table public.pipeline_runs (
    id bigint generated by default as identity primary key,

    variant_id bigint not null,

    run_timestamp timestamptz not null default now(),
    query_used text,
    confidence_threshold real,
    global_status varchar(64),
    verdict_note text,

    full_payload_json jsonb,
    payload_storage_path text,

    constraint pipeline_runs_variant_fk
        foreign key (variant_id)
        references public.variants(id)
        on delete cascade
);

-- Match the RLS configuration selected when these tables
-- were created in the Supabase dashboard.
alter table public.proteins enable row level security;
alter table public.variants enable row level security;
alter table public.clinical_cache enable row level security;
alter table public.biophysics_metrics enable row level security;
alter table public.pipeline_runs enable row level security;